### ISSUE TITLE
 lost a file during building sgx_detect.Dockerfile ?

### ISSUE THREAD

**Issue by bugxzhu** [Phala-Network/phala-docker#3]
Step 15/20 : ADD prebuilt/ra-test/app .
ADD failed: file not found in build context or excluded by .dockerignore: stat prebuilt/ra-test/app: file does not exist

**Comment by jasl** [comment]
You have to build from source <https://github.com/Phala-Network/ra-test>, because we use IAS so the SGX binary required private key signing that we can not public, I think I should rename the dockerfile to `prebuilt_sgx_detect.Dockerfile`
